<a href="https://colab.research.google.com/github/RasyaAkbar/learning-py-torch/blob/main/PyTorch%20Basic%20%2B%20Exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

2.4.0+cu121


Creating tensors

In [ ]:
scalar = torch.tensor(7)
print(scalar)

tensor(7)


In [ ]:
scalar.ndim

0

In [ ]:
scalar.item()

7

In [ ]:
vector = torch.tensor([7,7])
vector


tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
MATRIX = torch.tensor([[7,8], [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX[1]

tensor([ 9, 10])

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
TENSOR = torch.tensor([[[1,2,3], [3,6,9], [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

### Random tensors

In [ ]:
random_tensor = torch.rand(10, 4)
random_tensor

tensor([[0.6771, 0.6563, 0.9536, 0.3149],
        [0.1510, 0.0290, 0.1137, 0.8864],
        [0.0158, 0.2179, 0.7670, 0.8267],
        [0.4122, 0.9959, 0.6446, 0.8918],
        [0.1822, 0.3498, 0.7939, 0.3929],
        [0.4015, 0.9125, 0.1165, 0.6720],
        [0.4495, 0.6128, 0.4116, 0.3227],
        [0.5578, 0.4176, 0.4865, 0.5093],
        [0.3540, 0.3130, 0.4136, 0.4770],
        [0.3257, 0.9210, 0.8198, 0.7102]])

In [ ]:
random_image_size_tensor = torch.rand(size=(3, 224, 224)) #height weight color (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

In [ ]:
ones = torch.ones(3, 4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
zeros = torch.zeros(3, 4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
ones.dtype

torch.float32

### Creating a range of tensors and tensors-like


In [ ]:
one_to_ten = torch.arange(1, 11, 1)

In [ ]:
# Creating tensors like
ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensor datatypes

In [ ]:
float_32_tensor = torch.tensor ([3.0, 6.0, 9.0],
                               dtype = None, # tensor data type, this tensor default is 32 bit
                               device=None, # What device is your tensor on
                               requires_grad=False) # wheter or not to track gradients with this tensor operations)
float_16_tensor = float_32_tensor.type(torch.float16)
float_32_tensor.dtype, float_16_tensor.dtype, float_16_tensor.device

(torch.float32, torch.float16, device(type='cpu'))

In [ ]:
float_32_tensor * float_16_tensor

tensor([ 9., 36., 81.])

## Manipulating Tensors

In [ ]:
tensor = torch.tensor([[1, 2, 3],[4, -1, 6]])
tensor2 = torch.tensor([[7,8],[9,10],[11,12]])
tensor * 10, tensor + 10

(tensor([[ 10,  20,  30],
         [ 40, -10,  60]]),
 tensor([[11, 12, 13],
         [14,  9, 16]]))

In [ ]:
%%time
torch.matmul(tensor, tensor2), torch.mean(tensor.type(torch.float32)), tensor.type(torch.float32).mean()

CPU times: user 2.05 ms, sys: 0 ns, total: 2.05 ms
Wall time: 7.83 ms


(tensor([[58, 64],
         [85, 94]]),
 tensor(2.5000),
 tensor(2.5000))

In [ ]:
torch.matmul(torch.rand(2,1,3,3), torch.rand(2,3,3,3)), tensor.argmin(), tensor.shape

(tensor([[[[1.1807, 1.5994, 0.4803],
           [1.3534, 1.5706, 0.8213],
           [1.0944, 1.3481, 0.5559]],
 
          [[1.0722, 1.6344, 0.9488],
           [1.2175, 1.4565, 0.8206],
           [0.9947, 1.2462, 0.6561]],
 
          [[0.8103, 0.6701, 1.1966],
           [0.9669, 0.8113, 0.9073],
           [0.7327, 0.6755, 0.8706]]],
 
 
         [[[0.6473, 0.5627, 0.6227],
           [0.9196, 0.4160, 0.9261],
           [0.7801, 0.4463, 0.7862]],
 
          [[0.6057, 0.3430, 0.3566],
           [0.8087, 0.5568, 0.4227],
           [0.6336, 0.4550, 0.4305]],
 
          [[0.7832, 0.4293, 1.0134],
           [0.8898, 0.7808, 1.1597],
           [0.8022, 0.6463, 1.0112]]]]),
 tensor(4),
 torch.Size([2, 3]))

## Reshaping, stacking, squeezing, and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combines multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - remmoves all "1" dimensions from a tensor
* Unsqueeze - add a "1" dimension to a target tensor
* Permute - Return a view of the input with dimensions permuted (swapped) in a certain way

In [ ]:
x = torch.arange(1.,10.)
x, x.reshape(1, 9), x.reshape(9, 1), x.reshape(3, 3) # x.reshape(x, y) x*y == x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]),
 tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]))

In [ ]:
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
z[:, 0] = 9 # changes z also change x because they share the same memory
z, x

(tensor([[9., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([9., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
x_stacked = torch.stack([x,x,x,x], dim=1)
x_stacked, z.squeeze(), z.unsqueeze(dim=0)

(tensor([[9., 9., 9., 9.],
         [2., 2., 2., 2.],
         [3., 3., 3., 3.],
         [4., 4., 4., 4.],
         [5., 5., 5., 5.],
         [6., 6., 6., 6.],
         [7., 7., 7., 7.],
         [8., 8., 8., 8.],
         [9., 9., 9., 9.]]),
 tensor([9., 2., 3., 4., 5., 6., 7., 8., 9.]),
 tensor([[[9., 2., 3., 4., 5., 6., 7., 8., 9.]]]))

In [ ]:
random_tensor = torch.rand(1,2,3)
r_permuted = random_tensor.permute(1, 2, 0) # permuted and og share the same memory so can be prone to mutation!
r_permuted.shape

torch.Size([2, 3, 1])

## Indexing (selecting data from tensors)
Indexing with pytorch is similar to indexing with numpy
(i skip this section bcuz i think its intuitive enough, but def need to practice)


## Numpy & pyTorch

In [ ]:
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array) # warning: this reflects numpy default data type
array = array + 1 # this dont mutate each other even with tensor.numpy() tensor = tensor +1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
array.dtype, tensor.dtype, torch.arange(1.0, 8.0).dtype

(dtype('float64'), torch.float64, torch.float32)

In [ ]:
numpy_tensor = torch.arange(1.0, 8.0).numpy()
numpy_tensor.dtype

dtype('float32')

## Reproducibility (trying to take the random out of random)
As you learn more about neural networks and machine learning, you'll start to discover how much randomness plays a part.

Well, pseudorandomness that is. Because after all, as they're designed, a computer is fundamentally deterministic (each step is predictable) so the randomness they create are simulated randomness (though there is debate on this too, but since I'm not a computer scientist, I'll let you find out more yourself).

How does this relate to neural networks and deep learning then?

We've discussed neural networks start with random numbers to describe patterns in data (these numbers are poor descriptions) and try to improve those random numbers using tensor operations (and a few other things we haven't discussed yet) to better describe patterns in data.

In short:

start with random numbers -> tensor operations -> try to make better (again and again and again)

Although randomness is nice and powerful, sometimes you'd like there to be a little less randomness.

Why?

So you can perform repeatable experiments.

For example, you create an algorithm capable of achieving X performance.

And then your friend tries it out to verify you're not crazy.

How could they do such a thing?

That's where reproducibility comes in.

In other words, can you get the same (or very similar) results on your computer running the same code as I get on mine?

Let's see a brief example of reproducibility in PyTorch.

We'll start by creating two random tensors, since they're random, you'd expect them to be different right?

In [ ]:
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_A = torch.rand(4,4) #generate based on seed

random_tensor_B = torch.rand(4,4)

torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(4,4) #generate based on seed

random_tensor_A == random_tensor_B, random_tensor_A == random_tensor_C

(tensor([[False, False, False, False],
         [False, False, False, False],
         [False, False, False, False],
         [False, False, False, False]]),
 tensor([[True, True, True, True],
         [True, True, True, True],
         [True, True, True, True],
         [True, True, True, True]]))

In [ ]:
torch.cuda.is_available(), torch.cuda.device_count()

(False, 0)

In [ ]:
import torch
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [ ]:
tensor = torch.tensor([1, 2, 3])
tensor_on_gpu = tensor.to(device) # if tensor on gpu, cant transform it into numpy so need to revert to cpu first
tensor_on_gpu, tensor_on_gpu.cpu().numpy()

(tensor([1, 2, 3], device='cuda:0'), array([1, 2, 3]))

## Exercise

In [ ]:
import torch
random_tensor = torch.rand(7, 7)
random_tensor2 = torch.rand(1, 7)
torch.matmul(random_tensor, random_tensor2.T)

tensor([[1.1953],
        [1.2669],
        [1.4024],
        [1.4055],
        [0.9399],
        [1.1526],
        [0.4781]])

In [ ]:
torch.manual_seed(0)
random_tensor = torch.rand(7, 7)
#torch.manual_seed(0)
random_tensor2 = torch.rand(1, 7)
torch.matmul(random_tensor, random_tensor2.T)

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

In [ ]:
# Set seeds for CPU and GPU operations
torch.manual_seed(1234)

torch.cuda.manual_seed_all(1234)  # if you are using multi-GPU.
torch.backends.cudnn.deterministic = True
torch.backends.cudnn.benchmark = False

In [ ]:
torch.cuda.manual_seed(1234)
on_gpu = torch.rand(2,3, device="cuda")
on_gpu2 = torch.rand(3,2, device="cuda")
result = torch.matmul(on_gpu, on_gpu2)
result

tensor([[0.4446, 1.0074],
        [0.6217, 1.3363]], device='cuda:0')

In [ ]:
torch.manual_seed(7)
on_gpu = torch.rand(1, 1, 1, 10, device="cpu")
on_gpu2 = on_gpu.squeeze()
on_gpu, on_gpu2, on_gpu.shape, on_gpu2.shape, on_gpu.min(), on_gpu.max(), on_gpu.argmin(), on_gpu.argmax()

(tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
            0.3653, 0.8513]]]]),
 tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
         0.8513]),
 torch.Size([1, 1, 1, 10]),
 torch.Size([10]),
 tensor(0.1988),
 tensor(0.8513),
 tensor(1),
 tensor(9))